workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Clean CocoaPods and Derived Data
        script: |
          cd ios
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf Pods Podfile.lock
          pod deintegrate || true
          pod install --verbose
          pod repo update

      - name: Regenerate Scheme
        script: |
          cd ios
          # Ensure scheme is available and shared
          xcodebuild -list -workspace Runner.xcworkspace
          xcodebuild -scheme Runner -workspace Runner.xcworkspace -configuration Debug build -allowProvisioningUpdates

      - name: Build iOS app
        script: |
          set -o pipefail && flutter build ios --release --no-codesign | xcpretty

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
