workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60 # Set max build time in minutes
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APPLE_SIGNIN_EMAIL: $APPLE_SIGNIN_EMAIL
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - kumardigamberjha@gmail.com # Replace with your email

      # Optional: Add App Store publishing
      app_store_connect:
        apple_id: $APPLE_SIGNIN_EMAIL
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        ipa_path: build/ios/iphoneos/Runner.ipa
