workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      # Set up environment with Flutter and CocoaPods
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS
        script: flutter build ios --release
