workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods --no-document || true
          pod repo update

      - name: Clean up Pods and install dependencies
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate || true
          pod install --verbose
          pod repo update

      - name: Ensure Scheme Supports Build Action
        script: |
          # Display all available schemes
          xcodebuild -list -workspace ios/Runner.xcworkspace
          # Regenerate the Runner scheme if necessary
          xcodebuild -scheme Runner -workspace ios/Runner.xcworkspace -configuration Debug
          # Make sure the scheme is shared and supports the build action
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release build -allowProvisioningUpdates

      - name: Build iOS app
        script: |
          set -o pipefail && flutter build ios --release --no-codesign | xcpretty

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
