workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods --no-document || true
          pod repo update

      - name: Clean up Pods and install dependencies
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate || true
          pod install --verbose
          pod repo update

      - name: Regenerate Runner Scheme
        script: |
          cd ios
          # Create a new scheme for the Runner project if it's not properly configured
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Debug build -list
          # Ensure the scheme is shared
          xcodebuild -project Runner.xcodeproj -scheme Runner -configuration Release -derivedDataPath build
          # Share the scheme
          xcrun xcodebuild -project Runner.xcodeproj -scheme Runner -list

      - name: Build iOS app
        script: |
          set -o pipefail && flutter build ios --release --no-codesign | xcpretty

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
