workflows:
  build_ios_unsigned:
    name: Build iOS App without Signing
    instance_type: mac_mini
    environment:
      vars:
        FLUTTER_CHANNEL: stable
    triggering:
      events:
        - push
    scripts:
      - name: Set up Flutter
        script: |
          # Install Flutter and switch to the desired channel
          git clone https://github.com/flutter/flutter.git
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter channel $FLUTTER_CHANNEL
          flutter upgrade
          flutter doctor -v
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS unsigned release
        script: |
          # Build the app in release mode without code signing
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - kumardigamberjha@gmail.com
